WITH PERIOD_ANNUEL as (
SELECT DISTINCT NO_PER
		, DATE_FIN_PER
        , COUNT(DATE_FIN_PER) as VOTE
		, IIF(MONTH(DATE_FIN_PER) >= 7, YEAR(DATE_FIN_PER), YEAR(DATE_FIN_PER) - 1) as PER_YEAR
FROM {{ref("i_pai_hchq_per_paie")}}
WHERE DATE_FIN_PER >= DATEADD(YEAR,-5,GETDATE())
GROUP BY NO_PER, DATE_FIN_PER
),

PERIOD_ANNUEL_MAX_VOTE as (
	SELECT NO_PER
			, PER_YEAR
			, MAX(VOTE) as VOTE_MAX
	FROM PERIOD_ANNUEL
	GROUP BY NO_PER, PER_YEAR
),

PERIODES as (
	SELECT pa.*
	FROM PERIOD_ANNUEL pa
	INNER JOIN PERIOD_ANNUEL_MAX_VOTE mx ON pa.PER_YEAR = mx.PER_YEAR AND pa.VOTE = mx.VOTE_MAX AND pa.NO_PER = mx.NO_PER
),

MAX_PER_ANNUEL as (
	SELECT MAX(NO_PER) as MAX_PER
			, PER_YEAR as ANNEE
	FROM PERIODES
	GROUP BY PER_YEAR
),

PERIOD_ANNUEL_AVEC_IND_DERNIERE_PER as (
	SELECT per.*
			, IIF(MAX_PER IS NULL, 0, 1) as IND_DERNIERE_PERIOD_ANNUEL
	FROM PERIODES per
	LEFT JOIN MAX_PER_ANNUEL ON per.PER_YEAR = ANNEE AND NO_PER = MAX_PER
),

DUREE_PERIOD as (
	SELECT nex.*
			, DATEDIFF(day, base.DATE_FIN_PER, nex.DATE_FIN_PER) as NB_JOURS_PER
	FROM PERIOD_ANNUEL_AVEC_IND_DERNIERE_PER base
	LEFT JOIN PERIODES nex ON base.PER_YEAR = nex.PER_YEAR AND base.NO_PER + 1 = nex.NO_PER OR (base.PER_YEAR + 1 = nex.PER_YEAR AND base.IND_DERNIERE_PERIOD_ANNUEL = 1 AND nex.NO_PER = 1)
	WHERE nex.PER_YEAR IS NOT NULL
)

SELECT * FROM DUREE_PERIOD
